-- Create products table with all fields
CREATE TABLE IF NOT EXISTS public.products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  collection TEXT,
  size TEXT,
  seo_title TEXT NOT NULL,
  seo_description TEXT NOT NULL,
  keywords TEXT NOT NULL,
  image_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Create index on slug for performance
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_collection ON public.products(collection);

-- Enable RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public can view published products"
ON public.products
FOR SELECT
USING (status = 'draft' OR status = 'published');

-- Allow authenticated users to read all
CREATE POLICY "Authenticated users can view all products"
ON public.products
FOR SELECT
TO authenticated
USING (true);

-- Create function to generate slug
CREATE OR REPLACE FUNCTION generate_slug(input_text TEXT)
RETURNS TEXT AS $$
DECLARE
  slug TEXT;
BEGIN
  slug := lower(input_text);
  slug := regexp_replace(slug, '[áàâãä]', 'a', 'g');
  slug := regexp_replace(slug, '[éèêë]', 'e', 'g');
  slug := regexp_replace(slug, '[íìîï]', 'i', 'g');
  slug := regexp_replace(slug, '[óòôõö]', 'o', 'g');
  slug := regexp_replace(slug, '[úùûü]', 'u', 'g');
  slug := regexp_replace(slug, '[ç]', 'c', 'g');
  slug := regexp_replace(slug, '[^a-z0-9\s-]', '', 'g');
  slug := regexp_replace(slug, '\s+', '-', 'g');
  slug := regexp_replace(slug, '-+', '-', 'g');
  slug := trim(both '-' from slug);
  RETURN slug;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- Insert all 110 products with automatic SEO generation

-- Coberdrom Belissima (6 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Coberdrom Belissima 1', generate_slug('Coberdrom Belissima 1'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 1 | Aconchego e estilo', 'Coberdrom Belissima 1. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft'),
('Coberdrom Belissima 2', generate_slug('Coberdrom Belissima 2'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 2 | Aconchego e estilo', 'Coberdrom Belissima 2. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft'),
('Coberdrom Belissima 3', generate_slug('Coberdrom Belissima 3'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 3 | Aconchego e estilo', 'Coberdrom Belissima 3. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft'),
('Coberdrom Belissima 4', generate_slug('Coberdrom Belissima 4'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 4 | Aconchego e estilo', 'Coberdrom Belissima 4. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft'),
('Coberdrom Belissima 5', generate_slug('Coberdrom Belissima 5'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 5 | Aconchego e estilo', 'Coberdrom Belissima 5. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft'),
('Coberdrom Belissima 6', generate_slug('Coberdrom Belissima 6'), 'coberdrom', 'Belissima', '', 'Coberdrom Belissima 6 | Aconchego e estilo', 'Coberdrom Belissima 6. Peça versátil que garante aquecimento e estilo em qualquer estação. Visual premium e manutenção simples para um quarto sempre aconchegante.', 'coberdrom, aconchego, decoracao, quarto, belissima', 'draft');

-- Colcha Nina (4 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Colcha Nina 1', generate_slug('Colcha Nina 1'), 'colcha', 'Nina', '', 'Colcha Nina 1 | Elegância e praticidade', 'Colcha Nina 1. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina', 'draft'),
('Colcha Nina 2', generate_slug('Colcha Nina 2'), 'colcha', 'Nina', '', 'Colcha Nina 2 | Elegância e praticidade', 'Colcha Nina 2. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina', 'draft'),
('Colcha Nina 3', generate_slug('Colcha Nina 3'), 'colcha', 'Nina', '', 'Colcha Nina 3 | Elegância e praticidade', 'Colcha Nina 3. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina', 'draft'),
('Colcha Nina 4', generate_slug('Colcha Nina 4'), 'colcha', 'Nina', '', 'Colcha Nina 4 | Elegância e praticidade', 'Colcha Nina 4. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina', 'draft');

-- Colcha Nina Cetim (6 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Colcha Nina Cetim 1', generate_slug('Colcha Nina Cetim 1'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 1 | Elegância e praticidade', 'Colcha Nina Cetim 1. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft'),
('Colcha Nina Cetim 2', generate_slug('Colcha Nina Cetim 2'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 2 | Elegância e praticidade', 'Colcha Nina Cetim 2. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft'),
('Colcha Nina Cetim 3', generate_slug('Colcha Nina Cetim 3'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 3 | Elegância e praticidade', 'Colcha Nina Cetim 3. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft'),
('Colcha Nina Cetim 4', generate_slug('Colcha Nina Cetim 4'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 4 | Elegância e praticidade', 'Colcha Nina Cetim 4. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft'),
('Colcha Nina Cetim 5', generate_slug('Colcha Nina Cetim 5'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 5 | Elegância e praticidade', 'Colcha Nina Cetim 5. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft'),
('Colcha Nina Cetim 6', generate_slug('Colcha Nina Cetim 6'), 'colcha', 'Nina Cetim', '', 'Colcha Nina Cetim 6 | Elegância e praticidade', 'Colcha Nina Cetim 6. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, nina cetim', 'draft');

-- Colcha Roma (8 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Colcha Roma 1', generate_slug('Colcha Roma 1'), 'colcha', 'Roma', '', 'Colcha Roma 1 | Elegância e praticidade', 'Colcha Roma 1. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 2', generate_slug('Colcha Roma 2'), 'colcha', 'Roma', '', 'Colcha Roma 2 | Elegância e praticidade', 'Colcha Roma 2. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 3', generate_slug('Colcha Roma 3'), 'colcha', 'Roma', '', 'Colcha Roma 3 | Elegância e praticidade', 'Colcha Roma 3. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 4', generate_slug('Colcha Roma 4'), 'colcha', 'Roma', '', 'Colcha Roma 4 | Elegância e praticidade', 'Colcha Roma 4. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 5', generate_slug('Colcha Roma 5'), 'colcha', 'Roma', '', 'Colcha Roma 5 | Elegância e praticidade', 'Colcha Roma 5. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 6', generate_slug('Colcha Roma 6'), 'colcha', 'Roma', '', 'Colcha Roma 6 | Elegância e praticidade', 'Colcha Roma 6. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 7', generate_slug('Colcha Roma 7'), 'colcha', 'Roma', '', 'Colcha Roma 7 | Elegância e praticidade', 'Colcha Roma 7. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft'),
('Colcha Roma 8', generate_slug('Colcha Roma 8'), 'colcha', 'Roma', '', 'Colcha Roma 8 | Elegância e praticidade', 'Colcha Roma 8. Camada leve para finalizar a cama com visual alinhado. Fácil de combinar com fronhas, mantas e almofadas, garantindo praticidade e um décor elegante.', 'colcha, cama posta, decoracao, leve, pratica, roma', 'draft');

-- Edredom Casal (6 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Edredom Casal 1', generate_slug('Edredom Casal 1'), 'edredom', '', 'Casal', 'Edredom Casal 1 | Conforto e caimento perfeito', 'Edredom Casal 1. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft'),
('Edredom Casal 2', generate_slug('Edredom Casal 2'), 'edredom', '', 'Casal', 'Edredom Casal 2 | Conforto e caimento perfeito', 'Edredom Casal 2. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft'),
('Edredom Casal 3', generate_slug('Edredom Casal 3'), 'edredom', '', 'Casal', 'Edredom Casal 3 | Conforto e caimento perfeito', 'Edredom Casal 3. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft'),
('Edredom Casal 4', generate_slug('Edredom Casal 4'), 'edredom', '', 'Casal', 'Edredom Casal 4 | Conforto e caimento perfeito', 'Edredom Casal 4. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft'),
('Edredom Casal 5', generate_slug('Edredom Casal 5'), 'edredom', '', 'Casal', 'Edredom Casal 5 | Conforto e caimento perfeito', 'Edredom Casal 5. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft'),
('Edredom Casal 6', generate_slug('Edredom Casal 6'), 'edredom', '', 'Casal', 'Edredom Casal 6 | Conforto e caimento perfeito', 'Edredom Casal 6. Tamanho Casal. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, casal', 'draft');

-- Edredom Solteiro (6 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Edredom Solteiro 1', generate_slug('Edredom Solteiro 1'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 1 | Conforto e caimento perfeito', 'Edredom Solteiro 1. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft'),
('Edredom Solteiro 2', generate_slug('Edredom Solteiro 2'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 2 | Conforto e caimento perfeito', 'Edredom Solteiro 2. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft'),
('Edredom Solteiro 3', generate_slug('Edredom Solteiro 3'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 3 | Conforto e caimento perfeito', 'Edredom Solteiro 3. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft'),
('Edredom Solteiro 4', generate_slug('Edredom Solteiro 4'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 4 | Conforto e caimento perfeito', 'Edredom Solteiro 4. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft'),
('Edredom Solteiro 5', generate_slug('Edredom Solteiro 5'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 5 | Conforto e caimento perfeito', 'Edredom Solteiro 5. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft'),
('Edredom Solteiro 6', generate_slug('Edredom Solteiro 6'), 'edredom', '', 'Solteiro', 'Edredom Solteiro 6 | Conforto e caimento perfeito', 'Edredom Solteiro 6. Tamanho Solteiro. Aconchego com volume equilibrado, toque macio e acabamento resistente. Ideal para composições com colchas e jogos de cama, mantendo o quarto organizado e convidativo.', 'edredom, conforto, quarto, enxoval, macio, solteiro', 'draft');

-- Jogo de Cama Buzios (3 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Jogo de Cama Buzios 1 - Casal', generate_slug('Jogo de Cama Buzios 1 - Casal'), 'jogo-de-cama', 'Buzios', 'Casal', 'Jogo de Cama Buzios 1 - Casal | Conjunto confortável', 'Jogo de Cama Buzios 1 - Casal. Tamanho Casal, Linha Buzios. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, buzios, casal', 'draft'),
('Jogo de Cama Buzios 1 - Solteiro', generate_slug('Jogo de Cama Buzios 1 - Solteiro'), 'jogo-de-cama', 'Buzios', 'Solteiro', 'Jogo de Cama Buzios 1 - Solteiro | Conjunto confortável', 'Jogo de Cama Buzios 1 - Solteiro. Tamanho Solteiro, Linha Buzios. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, buzios, solteiro', 'draft'),
('Jogo de Cama Buzios 1', generate_slug('Jogo de Cama Buzios 1'), 'jogo-de-cama', 'Buzios', '', 'Jogo de Cama Buzios 1 | Conjunto confortável', 'Jogo de Cama Buzios 1. Linha Buzios. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, buzios', 'draft');

-- Jogo de Cama Ipanema (51 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Jogo de Cama Ipanema 1 - Casal', generate_slug('Jogo de Cama Ipanema 1 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 1 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 1 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 1 - Solteiro', generate_slug('Jogo de Cama Ipanema 1 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 1 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 1 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 1', generate_slug('Jogo de Cama Ipanema 1'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 1 | Conjunto confortável', 'Jogo de Cama Ipanema 1. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 10 - Casal', generate_slug('Jogo de Cama Ipanema 10 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 10 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 10 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 10 - Solteiro', generate_slug('Jogo de Cama Ipanema 10 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 10 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 10 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 10', generate_slug('Jogo de Cama Ipanema 10'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 10 | Conjunto confortável', 'Jogo de Cama Ipanema 10. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 11 - Casal', generate_slug('Jogo de Cama Ipanema 11 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 11 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 11 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 11 - Solteiro', generate_slug('Jogo de Cama Ipanema 11 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 11 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 11 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 11', generate_slug('Jogo de Cama Ipanema 11'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 11 | Conjunto confortável', 'Jogo de Cama Ipanema 11. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 12 - Casal', generate_slug('Jogo de Cama Ipanema 12 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 12 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 12 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 12 - Solteiro', generate_slug('Jogo de Cama Ipanema 12 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 12 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 12 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 12', generate_slug('Jogo de Cama Ipanema 12'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 12 | Conjunto confortável', 'Jogo de Cama Ipanema 12. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 13 - Casal', generate_slug('Jogo de Cama Ipanema 13 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 13 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 13 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 13 - Solteiro', generate_slug('Jogo de Cama Ipanema 13 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 13 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 13 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 13', generate_slug('Jogo de Cama Ipanema 13'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 13 | Conjunto confortável', 'Jogo de Cama Ipanema 13. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 14 - Casal', generate_slug('Jogo de Cama Ipanema 14 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 14 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 14 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 14 - Solteiro', generate_slug('Jogo de Cama Ipanema 14 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 14 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 14 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 14', generate_slug('Jogo de Cama Ipanema 14'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 14 | Conjunto confortável', 'Jogo de Cama Ipanema 14. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 15 - Casal', generate_slug('Jogo de Cama Ipanema 15 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 15 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 15 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 15 - Solteiro', generate_slug('Jogo de Cama Ipanema 15 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 15 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 15 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 15', generate_slug('Jogo de Cama Ipanema 15'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 15 | Conjunto confortável', 'Jogo de Cama Ipanema 15. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 16 - Casal', generate_slug('Jogo de Cama Ipanema 16 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 16 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 16 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 16 - Solteiro', generate_slug('Jogo de Cama Ipanema 16 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 16 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 16 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 16', generate_slug('Jogo de Cama Ipanema 16'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 16 | Conjunto confortável', 'Jogo de Cama Ipanema 16. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 17 - Casal', generate_slug('Jogo de Cama Ipanema 17 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 17 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 17 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 17 - Solteiro', generate_slug('Jogo de Cama Ipanema 17 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 17 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 17 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 17', generate_slug('Jogo de Cama Ipanema 17'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 17 | Conjunto confortável', 'Jogo de Cama Ipanema 17. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 2 - Casal', generate_slug('Jogo de Cama Ipanema 2 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 2 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 2 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 2 - Solteiro', generate_slug('Jogo de Cama Ipanema 2 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 2 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 2 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 2', generate_slug('Jogo de Cama Ipanema 2'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 2 | Conjunto confortável', 'Jogo de Cama Ipanema 2. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 3 - Casal', generate_slug('Jogo de Cama Ipanema 3 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 3 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 3 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 3 - Solteiro', generate_slug('Jogo de Cama Ipanema 3 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 3 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 3 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 3', generate_slug('Jogo de Cama Ipanema 3'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 3 | Conjunto confortável', 'Jogo de Cama Ipanema 3. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 4 - Casal', generate_slug('Jogo de Cama Ipanema 4 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 4 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 4 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 4 - Solteiro', generate_slug('Jogo de Cama Ipanema 4 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 4 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 4 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 4', generate_slug('Jogo de Cama Ipanema 4'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 4 | Conjunto confortável', 'Jogo de Cama Ipanema 4. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 5 - Casal', generate_slug('Jogo de Cama Ipanema 5 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 5 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 5 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 5 - Solteiro', generate_slug('Jogo de Cama Ipanema 5 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 5 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 5 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 5', generate_slug('Jogo de Cama Ipanema 5'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 5 | Conjunto confortável', 'Jogo de Cama Ipanema 5. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 6 - Casal', generate_slug('Jogo de Cama Ipanema 6 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 6 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 6 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 6 - Solteiro', generate_slug('Jogo de Cama Ipanema 6 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 6 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 6 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 6', generate_slug('Jogo de Cama Ipanema 6'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 6 | Conjunto confortável', 'Jogo de Cama Ipanema 6. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 7 - Solteiro', generate_slug('Jogo de Cama Ipanema 7 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 7 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 7 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 7', generate_slug('Jogo de Cama Ipanema 7'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 7 | Conjunto confortável', 'Jogo de Cama Ipanema 7. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 8 - Casal', generate_slug('Jogo de Cama Ipanema 8 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 8 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 8 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 8 - Solteiro', generate_slug('Jogo de Cama Ipanema 8 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 8 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 8 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 8', generate_slug('Jogo de Cama Ipanema 8'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 8 | Conjunto confortável', 'Jogo de Cama Ipanema 8. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft'),
('Jogo de Cama Ipanema 9 - Casal', generate_slug('Jogo de Cama Ipanema 9 - Casal'), 'jogo-de-cama', 'Ipanema', 'Casal', 'Jogo de Cama Ipanema 9 - Casal | Conjunto confortável', 'Jogo de Cama Ipanema 9 - Casal. Tamanho Casal, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, casal', 'draft'),
('Jogo de Cama Ipanema 9 - Solteiro', generate_slug('Jogo de Cama Ipanema 9 - Solteiro'), 'jogo-de-cama', 'Ipanema', 'Solteiro', 'Jogo de Cama Ipanema 9 - Solteiro | Conjunto confortável', 'Jogo de Cama Ipanema 9 - Solteiro. Tamanho Solteiro, Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema, solteiro', 'draft'),
('Jogo de Cama Ipanema 9', generate_slug('Jogo de Cama Ipanema 9'), 'jogo-de-cama', 'Ipanema', '', 'Jogo de Cama Ipanema 9 | Conjunto confortável', 'Jogo de Cama Ipanema 9. Linha Ipanema. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, ipanema', 'draft');

-- Jogo de Cama Milão (12 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Jogo de Cama Milão 1 - Casal', generate_slug('Jogo de Cama Milão 1 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 1 - Casal | Conjunto confortável', 'Jogo de Cama Milão 1 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 1', generate_slug('Jogo de Cama Milão 1'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 1 | Conjunto confortável', 'Jogo de Cama Milão 1. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft'),
('Jogo de Cama Milão 2 - Casal', generate_slug('Jogo de Cama Milão 2 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 2 - Casal | Conjunto confortável', 'Jogo de Cama Milão 2 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 2', generate_slug('Jogo de Cama Milão 2'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 2 | Conjunto confortável', 'Jogo de Cama Milão 2. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft'),
('Jogo de Cama Milão 3 - Casal', generate_slug('Jogo de Cama Milão 3 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 3 - Casal | Conjunto confortável', 'Jogo de Cama Milão 3 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 3', generate_slug('Jogo de Cama Milão 3'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 3 | Conjunto confortável', 'Jogo de Cama Milão 3. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft'),
('Jogo de Cama Milão 4 - Casal', generate_slug('Jogo de Cama Milão 4 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 4 - Casal | Conjunto confortável', 'Jogo de Cama Milão 4 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 4', generate_slug('Jogo de Cama Milão 4'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 4 | Conjunto confortável', 'Jogo de Cama Milão 4. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft'),
('Jogo de Cama Milão 5 - Casal', generate_slug('Jogo de Cama Milão 5 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 5 - Casal | Conjunto confortável', 'Jogo de Cama Milão 5 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 5', generate_slug('Jogo de Cama Milão 5'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 5 | Conjunto confortável', 'Jogo de Cama Milão 5. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft'),
('Jogo de Cama Milão 6 - Casal', generate_slug('Jogo de Cama Milão 6 - Casal'), 'jogo-de-cama', 'Milao', 'Casal', 'Jogo de Cama Milão 6 - Casal | Conjunto confortável', 'Jogo de Cama Milão 6 - Casal. Tamanho Casal, Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao, casal', 'draft'),
('Jogo de Cama Milão 6', generate_slug('Jogo de Cama Milão 6'), 'jogo-de-cama', 'Milao', '', 'Jogo de Cama Milão 6 | Conjunto confortável', 'Jogo de Cama Milão 6. Linha Milão. Conjunto essencial com toque agradável e caimento bonito. Perfeito para uso diário, fácil de lavar e combinar com edredons e colchas.', 'jogo de cama, lencol, fronhas, enxoval, conforto, milao', 'draft');

-- Travesseiro Alvorada (2 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Travesseiro Alvorada 2', generate_slug('Travesseiro Alvorada 2'), 'travesseiro', 'Alvorada', '', 'Travesseiro Alvorada 2 | Suporte e maciez', 'Travesseiro Alvorada 2. Linha Alvorada. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, alvorada', 'draft'),
('Travesseiro Alvorada', generate_slug('Travesseiro Alvorada'), 'travesseiro', 'Alvorada', '', 'Travesseiro Alvorada | Suporte e maciez', 'Travesseiro Alvorada. Linha Alvorada. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, alvorada', 'draft');

-- Travesseiro Bom Sono (2 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Travesseiro Bom Sono 2', generate_slug('Travesseiro Bom Sono 2'), 'travesseiro', 'Bom Sono', '', 'Travesseiro Bom Sono 2 | Suporte e maciez', 'Travesseiro Bom Sono 2. Linha Bom Sono. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, bom sono', 'draft'),
('Travesseiro Bom Sono', generate_slug('Travesseiro Bom Sono'), 'travesseiro', 'Bom Sono', '', 'Travesseiro Bom Sono | Suporte e maciez', 'Travesseiro Bom Sono. Linha Bom Sono. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, bom sono', 'draft');

-- Travesseiro Delicata (2 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Travesseiro Delicata 2', generate_slug('Travesseiro Delicata 2'), 'travesseiro', 'Delicata', '', 'Travesseiro Delicata 2 | Suporte e maciez', 'Travesseiro Delicata 2. Linha Delicata. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, delicata', 'draft'),
('Travesseiro Delicata', generate_slug('Travesseiro Delicata'), 'travesseiro', 'Delicata', '', 'Travesseiro Delicata | Suporte e maciez', 'Travesseiro Delicata. Linha Delicata. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, delicata', 'draft');

-- Travesseiro Nuvare (2 products)
INSERT INTO public.products (name, slug, category, collection, size, seo_title, seo_description, keywords, status) VALUES
('Travesseiro Nuvare 2', generate_slug('Travesseiro Nuvare 2'), 'travesseiro', 'Nuvare', '', 'Travesseiro Nuvare 2 | Suporte e maciez', 'Travesseiro Nuvare 2. Linha Nuvare. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, nuvare', 'draft'),
('Travesseiro Nuvare', generate_slug('Travesseiro Nuvare'), 'travesseiro', 'Nuvare', '', 'Travesseiro Nuvare | Suporte e maciez', 'Travesseiro Nuvare. Linha Nuvare. Equilíbrio entre suporte e maciez para noites mais confortáveis. Durável e fácil de cuidar, ideal para completar o enxoval.', 'travesseiro, suporte, maciez, descanso, nuvare', 'draft');

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();