// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npwtckrpcfogeqkticse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wd3Rja3JwY2ZvZ2Vxa3RpY3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4NzcyMTUsImV4cCI6MjA3NTQ1MzIxNX0.gesbjNrEYsmE4lSW42TTBJfO2r7dcX4olOqdHNvtCK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});